### PR TITLE
Changed SignInResponseGenerator.CreateSubjectAsync access modifier

### PR DESCRIPTION
**Pull request by vidarkongsli**
Ref. issue #69

### CODE REVIEW

**Comment by leastprivilege** [comment]
any objections? @brockallen @scottbrady91

**Comment by scottbrady91** [comment]
If you're happy, then I'm happy.

**Comment by leastprivilege** [comment]
is it a breaking change? can't remember.

**Comment by scottbrady91** [comment]
No, switching from private to protected (in order to test a method) won't be a breaking change. Going back would be...

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
