### PR TITLE
Proposed fix for issue #27

### PR DESCRIPTION
**Pull request by magnus-ahlberg-stratsys**
This PR is copied from
https://github.com/IdentityServer/IdentityServer3.WsFederation/pull/34

All cred goes to santiagovm

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks.

Sorry I haven't diffed your PR and the one fro Santiagovm - why another PR?

**Comment by magnus-ahlberg-stratsys** [comment]
You told him too make another in dev and i could not find one. If there is. Please discard this one :)

**Comment by leastprivilege** [comment]
this one? https://github.com/IdentityServer/IdentityServer3.WsFederation/pull/35

**Comment by magnus-ahlberg-stratsys** [comment]
Most likely. Discard this one then.

**Comment by leastprivilege** [comment]
thanks anyways ;)

**Pull request closed without merging**
