### PR TITLE
ADFS won't import idsrv3 metadata

### PR DESCRIPTION
**Pull request by nzpcmad**
Add ApplicationServiceDescriptor - based on the ADFS metadata. This
metadata file does import into ADFS without issues.

### CODE REVIEW

**Comment by leastprivilege** [comment]
looks good! thanks!

**Comment by leastprivilege** [comment]
argh - it was done on master. We don't accept PRs on master - my fault.

**Comment by nzpcmad** [comment]
Me bad!

Apologies - I'm happy to repeat on Dev if you want.Like I said, I don't use
GitHub - all part of the learning process!

Thanks

**Comment by leastprivilege** [comment]
don't worry - i've taken care of it. The nuget has been released already.

**Pull request merged**
